flowacademyhu/theta-test-aggregator

backend/src/app/routers/user.ts
=> I15 user router

backend/src/lib/querryParamHandlers/filterCommitHash.ts, backend/src/lib/querryParamHandlers/filterEndTimeRange.ts, backend/src/lib/querryParamHandlers/filterStartTimeRange.ts, backend/src/lib/querryParamHandlers/filterStatus.ts, backend/src/lib/querryParamHandlers/filterTriggeredBy.ts
#20 created filters for GET simulation_results
=> I20 filter simulation results

backend/src/app/routers/simulationResult.ts
#16 created simulationResult router
=> I16-Simulation_result router

backend/migrations/20200616083001_create-simulation-results.js, backend/migrations/20200617081012_simulation-result-seq_num-to-auto_increment.js, backend/src/app/models/simulationResult.ts
#13 Created model interface and migration
=> I13 simulation model migration

backend/seeds/00-example-users.js, backend/seeds/01-example-simulation-results.js
#67 Created temporary data for db tables.
=> I67 database seeds

backend/migrations/20200618125513_create-users.js, backend/src/app/controllers/authorization.ts, backend/src/app/controllers/login.ts, backend/src/app/controllers/simulationResult.ts, backend/src/app/controllers/user.ts, backend/src/app/models/simulationResult.ts, backend/src/app/models/user.ts, backend/src/app/serializers/user.ts, backend/src/index.ts, backend/src/lib/authentication.ts, backend/src/lib/enums.ts, backend/src/lib/enums/enum.ts
#66 
migration create-user
enum.ts create
index.ts update
controllers, model, authentiation change
=> I66 enum and migra

backend/config/swagger.json
=> I61 swagger first version

backend/src/app/routers/index.ts
=> I77 prefix path

backend/config/swagger.json, backend/package.json, backend/src/index.ts
#83 
fixed swagger-ui packages
=> I83 swagger ui

backend/migrations/20200617081012_simulation-result-seq_num-to-auto_increment.js, backend/migrations/20200618131631_create-api_keys.js, backend/src/app/models/apiKey.ts
Created migration and interface for API keys
=> I70 api key migration interface

backend/config/swagger.json, backend/package.json, backend/src/app/controllers/user.ts, backend/src/app/models/user.ts, backend/src/app/serializers/user.ts
#90 
Added uuid npm package
Added generateUUID method to controller
Fixed variable names and paths in swagger, controller and serializer
=> I90 user UUID swagger fix

backend/src/app/routers/apiKey.ts, backend/src/app/routers/index.ts
=> I95 apikey router

backend/config/swagger.json
=> I96-apikey-swagger

backend/config/swagger.json, backend/migrations/20200622081739_simulation-result-timestamp-fix.js, backend/src/app/controllers/simulationResult.ts, backend/src/app/models/simulationResult.ts
#93 
Fixed simulation result timestamp type in database
Added decode to payload
Edited swagger and model
=> I93 simulation result fix

backend/config/swagger.json, backend/src/app/controllers/simulationResult.ts, backend/src/app/routers/simulationResult.ts
#22 
added invalidate method to controller
edited router to include invalidate
edited swagger to include invalidate
added authorization to router
=> I22 test result invalidate

backend/src/lib/tableName.ts
=> I109-API_KEY tablename add

backend/config/swagger.json
=> I111-swagger fix

backend/src/lib/authentication.ts, backend/src/lib/queryParamHandlers/filterEndTimeRange.ts, backend/src/lib/queryParamHandlers/filterStartTimeRange.ts, backend/src/lib/queryParamHandlers/limit.ts, backend/src/lib/queryParamHandlers/offset.ts
#104 
fixed filter query methods
fixed typos and login path in authentication.ts
=> I104 filter fix

frontend/src/app/models/test.model.ts
=> I106 create test model (#106)

frontend/src/app/components/header/header.component.css, frontend/src/app/components/header/header.component.html
#113 
Cursor changes to pointer on hover over header elements
=> I113 Cursor to pointer fix

backend/seeds/00-example-users.js
=> I120 seed user update

frontend/src/app/app.module.ts, frontend/src/app/components/header/header.component.ts, frontend/src/app/components/logged-in/logged-in.component.ts, frontend/src/app/components/login/login.component.ts
#124 resolver is put back into app.module.ts and components now able to get the logged in user
=> I124 issues fixed

frontend/src/app/components/api-key-manager/api-key-manager.component.ts
=> I126-private to public fix

backend/docker-compose.yml, backend/migrations/20200625113444_update-api-key-expiration-type.js, backend/src/app/controllers/apiKey.ts
#119 
Created option to make an API key with current date + 500 years expiration
(post method at /api/apikey?infinite=true)
=> I119 infinite api key

backend/seeds/03-example-api-key.js
=> I132 created api-key seed

backend/seeds/01-example-simulation-results.js
=> I138 Duplicate ID fix

frontend/src/app/interceptors/token.interceptor.ts
=> I140 token interceptor quick fix

backend/src/app/models/statistic.ts
#143  model created for statistics
=> I143 create statistics model

backend/migrations/20200629130613_create-statistics.js, backend/src/app/models/statistic.ts, backend/src/lib/enums.ts, backend/src/lib/tableName.ts
#145 migration created for statistics
=> I145 create statistics table migration

frontend/src/app/app.module.ts, frontend/src/app/components/filters/filters.component.spec.ts, frontend/src/app/components/filters/filters.component.ts, frontend/src/app/components/test-results/test-results.component.html, frontend/src/app/components/test-results/test-results.component.ts, frontend/src/app/models/filter-params-model.ts, frontend/src/app/resolvers/tests.resolver.ts, frontend/src/app/services/test.service.ts
#37 
Created filters for triggered by and commit hash without styling.
=> I37 filter for triggered by and commit hash

backend/migrations/20200701104448_update-statistics.js, backend/src/app/controllers/simulationResult.ts, backend/src/app/controllers/statistic.ts, backend/src/app/models/statistic.ts, backend/src/app/serializers/statistic.ts
=> I150 statistic crud

frontend/src/app/auth.guard.ts, frontend/src/app/components/user/user.component.ts, frontend/src/app/services/auth.service.ts
=> I153 auth guard auto login

backend/config/swagger.json, backend/docker-compose.yml, backend/package.json, backend/src/app/controllers/login.ts, backend/src/app/controllers/user.ts, backend/src/app/models/idToken.ts, backend/src/app/models/user.ts, backend/src/app/routers/login.ts, backend/src/lib/authentication.ts
#19 
Implemented google authentication on backend
=> I19 google auth

frontend/package-lock.json, frontend/src/app/components/filters/filters.component.ts
=> I43 weekly failures

backend/config/swagger.json, backend/src/app/controllers/simulationResult.ts
#172 
Backend modification to no longer return invalid tests
=> I172 invalidate test be

backend/src/app/controllers/userProfile.ts
=> I177 userprofile bugfix

backend/config/swagger.json
=> I134 - swagger fix

backend/src/app/controllers/simulationResult.ts, backend/src/app/serializers/simulationResult.ts
#180 
Implemented simulation result serializer to reduce index response size
BE returns tests ordered by descending sequence_number
=> I180 simulation result serializer

frontend/src/app/app.module.ts, frontend/src/app/components/test-details/test-details.component.html, frontend/src/app/pipes/payload-text-prettify.pipe.spec.ts, frontend/src/app/pipes/payload-text-prettify.pipe.ts
#185 
Implemented JSON prettify pipe for payload text
=> I185 prettify payload text

frontend/package-lock.json, frontend/src/app/app.module.ts, frontend/src/app/components/filters/filters.component.css, frontend/src/app/components/filters/filters.component.html, frontend/src/app/components/filters/filters.component.ts
#179 To stay consistent I splitted html and css to separate files.
=> I179 filters.component.ts to .ts .html .css

backend/config/swagger.json, backend/src/app/serializers/statistic.ts
#186 statistic serializer and swagger changed to include simulation_result_id
=> I186 change statistic serializer

frontend/src/app/app.module.ts, frontend/src/app/components/test-details/test-details.component.html, frontend/src/app/components/test-details/test-details.component.ts, frontend/src/app/modals/confirm-invalidate-modal/confirm-invalidate-modal.component.css, frontend/src/app/modals/confirm-invalidate-modal/confirm-invalidate-modal.component.html, frontend/src/app/modals/confirm-invalidate-modal/confirm-invalidate-modal.component.spec.ts, frontend/src/app/modals/confirm-invalidate-modal/confirm-invalidate-modal.component.ts, frontend/src/app/services/test.service.ts
#41 
Implemented invalidate test button for admins
=> I41 invalidate test

frontend/src/app/components/header/header.component.html, frontend/src/app/components/user-list/user-list.component.html, frontend/src/app/components/user-list/user-list.component.ts, frontend/src/app/components/user/user.component.html, frontend/src/app/services/auth.service.ts
=> I174 bugfix google sign out and ctx undefined errors

frontend/src/app/models/statistic.model.ts
=> I190 statistic model created

frontend/src/app/services/statistics.service.spec.ts, frontend/src/app/services/statistics.service.ts
=> I192 statistics service created

frontend/src/app/components/api-key-manager/api-key-manager.component.html, frontend/src/app/components/api-key-manager/api-key-manager.component.ts, frontend/src/app/components/test-results/test-results.component.html, frontend/src/app/modals/add-apikey-modal/add-apikey-modal.component.html, frontend/src/app/modals/add-apikey-modal/add-apikey-modal.component.ts, frontend/src/app/services/apikey.service.ts
#169 add apikey + pagination bugfix
=> I169 add apikey

backend/migrations/20200706143814_user-email-unique.js
=> I194 - make email unique

frontend/src/app/components/test-details/test-details.component.css, frontend/src/app/components/test-details/test-details.component.html
=> I202 - open by default

backend/config/swagger.json, backend/src/app/controllers/simulationResult.ts
#213 
Updated and fixed swagger file to represent current changes
Updated simulationResult controller's initialize method to contain required fields
=> I213 swagger fix

backend/migrations/20200707121329_create-custom-filters.js
=> I212 custom filter migration

backend/src/app/models/customFilter.ts
=> I209 custom filter model

frontend/src/app/app.module.ts, frontend/src/app/services/route-reuse.service.spec.ts, frontend/src/app/services/route-reuse.service.ts
#205 
Implemented RouteReuseService to cache index page when navigating to test details page
=> I205 cache search

frontend/src/app/components/test-results/test-results.component.html, frontend/src/app/components/test-results/test-results.component.ts, frontend/src/app/models/filter-params-model.ts, frontend/src/app/models/testsResponse.model.ts, frontend/src/app/services/test.service.ts
#195 
Implemented server side pagination
=> I195 server side pagination

backend/config/swagger.json, backend/src/lib/queryParamHandlers/filterStartTimeRange.ts
=> I217 open ended date filter

backend/config/swagger.json, backend/migrations/20200707121329_create-custom-filters.js, backend/seeds/00-example-users.js, backend/src/app/controllers/customFilter.ts, backend/src/app/models/customFilter.ts, backend/src/app/routers/customFilter.ts, backend/src/app/routers/index.ts, backend/src/app/serializers/customFilter.ts, backend/src/lib/tableName.ts
crud and route created for custom filters
=> I208 custom filters crud

frontend/src/app/components/api-key-manager/api-key-manager.component.css, frontend/src/app/components/api-key-manager/api-key-manager.component.html, frontend/src/app/components/api-key-manager/api-key-manager.component.ts
+ disable extend expiration time for infinite apikey
=> I204 apikey layout

frontend/src/app/components/add-user/add-user.component.css, frontend/src/app/components/add-user/add-user.component.html, frontend/src/app/components/add-user/add-user.component.ts, frontend/src/app/components/login/login.component.css, frontend/src/app/components/login/login.component.html, frontend/src/app/components/login/login.component.ts
Error message-ek jelennek mostantól meg, ha már létező email-el regisztrálnánk vagy nem megfelelő email-jelszó párossal lépnénk be...
=> I219 add error messages to login and add user pages

frontend/src/app/app.module.ts, frontend/src/app/components/add-user/add-user.component.html, frontend/src/app/components/api-key-manager/api-key-manager.component.css, frontend/src/app/components/api-key-manager/api-key-manager.component.html, frontend/src/app/components/test-details/test-details.component.html, frontend/src/app/components/test-results/test-results.component.css, frontend/src/app/components/test-results/test-results.component.html, frontend/src/app/components/user-list/user-list.component.html, frontend/src/app/components/user/user.component.css, frontend/src/app/components/user/user.component.html, frontend/src/app/directives/back-button.directive.spec.ts, frontend/src/app/directives/back-button.directive.ts, frontend/src/styles.css
=> I206 back button directive

backend/src/index.ts
=> I224 env variable check

frontend/src/app/app.module.ts, frontend/src/app/components/login/login.component.css, frontend/src/app/components/login/login.component.html, frontend/src/app/components/login/login.component.ts, frontend/src/app/services/auth.service.ts
#229 
- redirectTo index added
- indentation and semicolon fixes
- remember me vertical align fix
=> I229 redirectTo index added

frontend/src/app/components/api-key-manager/api-key-manager.component.html
=> I227 - date format change

backend/seeds/04-example-statistics.js
=> I231 - seed created for statistics

backend/src/app/controllers/sendmail.ts
=> I234 sendmail bugfix

frontend/src/app/components/login/login.component.html, frontend/src/app/components/test-details/test-details.component.css
=> I233 Small design change
